// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsvkwedgiwwvnroghbzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzdmt3ZWRnaXd3dm5yb2doYnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NjQ2MTQsImV4cCI6MjA4NTA0MDYxNH0.8SwjQi8RFIUI4cUqHoViE3fIYc9pDL8fD-7gc1cOyUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});